spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .ftl
  profiles:
    active: native
---
server:
  port: 8080
logging:
  level:
   root: info
spring:
  profiles: native
---
server:
  port: 8080
logging:
  level:
    root: error
spring:
  profiles: prod

